### ISSUE TITLE
Filters don't update when adding a component via script

### ISSUE THREAD

**Issue by r2d2meuleu** [OlegDzhuraev/OsnovaFramework#2]
Hi, 

I just discovered your framework, and it looks cool.

I found what I think is a bug ; if I spawn a Prefab, it is registered correctly by the filters and used by the systems, but if I create a gameObject and add component via script, they don't register.

This is problematic as often you add component during the game to add conditions, states and such.

Here is the code used : 
The left click works correctly, the right doesn't.

```csharp
void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            Instantiate(myPrefab, new Vector3(0, 0, 0), Quaternion.identity);
        }
        if (Input.GetMouseButtonDown(1))
        {
            GameObject cubeObject = GameObject.CreatePrimitive(PrimitiveType.Cube);

            cubeObject.AddComponent<Entity>(); // actually not needed, managed by MoveComponent
            cubeObject.AddComponent<MoveComponent>();
            cubeObject.GetComponent<MoveComponent>().Speed = 0.2f;
            cubeObject.GetComponent<MoveComponent>().Direction = new Vector3(0, 1, 0);
        }
    }
```

I can maybe correct this myself, any pointers where to look at ?

Thank you

**Comment by OlegDzhuraev** [comment]
Hi! 

I do not planned that Entity component will be added from Unity Update cycle, so can not guarantee correct work in this case.

Actual approach is to spawn prefab with entity, and work with its components (Add/Get) from Systems code, classic MonoBehaviour is not recommended.

Anyway, your case should work too, I'll check it and write more.

**Comment by OlegDzhuraev** [comment]
Hi again!

Yes, this issue was in project, fixed it. Thanks for info!

But you also need to add component to the Entity object, not the game object. Actually ECS catches directly from object only components which was added on start. In future this can be changed.

In your case, correct code can look like this:

```cs
GameObject cubeObject = GameObject.CreatePrimitive(PrimitiveType.Cube);

var ent = cubeObject.AddComponent<Entity>();
var moveComponent = ent.Add<MoveComponent>();
moveComponent.Speed = 0.2f;
moveComponent.Direction = new Vector3(0, 1, 0);
````

**Comment by r2d2m** [comment]
Thank you, i'll check !
